[workspace]
members = [
    "authserver",
    "ipc_comms",
    "macros",
    "gameserver/packets",
    "authserver/authserver_migration",
    "authserver/authserver_entity",
    "gameserver",
    "gameserver/gameobjects",
    "gameserver/common",
]
resolver = "2"
package.license = "GPL-3.0-only"

[profile.dev]
package.bitfield-struct.opt-level = 3
package.sqlx-macros.opt-level = 3
package.macros.opt-level = 3
