[workspace]
members = [
    "authserver",
    "ipc_comms",
    "macros",
    "gameserver/packets",
    "authserver/authserver_migration",
    "authserver/authserver_entity",
    "gameserver",
    "gameserver/gameserver_migration",
    "gameserver/gameserver_entity",
    "gameserver/gameobjects",
    "gameserver/common",
]
resolver = "2"
