[workspace]
members = [
    "authserver",
    "ipc_comms",
    "macros",
    "gameserver/packets",
    "authserver/authserver_migration",
    "authserver/authserver_entity",
    "gameserver",
    "gameserver/gameobjects",
    "gameserver/common",
    "worldeditor",
    #"worldeditor/mpq",
    "worldeditor/dbc_structs",
    "worldeditor/dbd_reader",
    "worldeditor/dbc_reader"
]
resolver = "2"
package.license = "GPL-3.0-only"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
