/* ---------------- Game data START ---------------- */
CREATE TABLE IF NOT EXISTS item_prototype(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    class INT NOT NULL,
    sub_class INT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    display_id INT NOT NULL,
    quality INT NOT NULL,
    buy_price INT NOT NULL,
    sell_price INT NOT NULL,
    inventory_type TINYINT NOT NULL,
    allowable_class INT NOT NULL,
    allowable_race INT NOT NULL,
    item_level INT NOT NULL,
    required_level TINYINT NOT NULL,
    required_skill INT NOT NULL,
    required_skill_rank INT NOT NULL,
    required_spell INT NOT NULL,
    required_honor_rank INT NOT NULL,
    required_city_rank INT NOT NULL,
    required_reputation_faction INT NOT NULL,
    required_reputation_rank INT NOT NULL,
    max_count INT NOT NULL,
    stackable INT NOT NULL,
    container_slots INT NOT NULL,

    /* Item stats START */
    item_stat1_type INT NOT NULL,
    item_stat1_value INT NOT NULL,
    item_stat2_type INT NOT NULL,
    item_stat2_value INT NOT NULL,
    item_stat3_type INT NOT NULL,
    item_stat3_value INT NOT NULL,
    item_stat4_type INT NOT NULL,
    item_stat4_value INT NOT NULL,
    item_stat5_type INT NOT NULL,
    item_stat5_value INT NOT NULL,
    item_stat6_type INT NOT NULL,
    item_stat6_value INT NOT NULL,
    item_stat7_type INT NOT NULL,
    item_stat7_value INT NOT NULL,
    item_stat8_type INT NOT NULL,
    item_stat8_value INT NOT NULL,
    item_stat9_type INT NOT NULL,
    item_stat9_value INT NOT NULL,
    item_stat10_type INT NOT NULL,
    item_stat10_value INT NOT NULL,
    /* Item stats END */
    /* Item damage START */
    item_damage1_min INT NOT NULL,
    item_damage1_max INT NOT NULL,
    item_damage1_type INT NOT NULL,
    item_damage2_min INT NOT NULL,
    item_damage2_max INT NOT NULL,
    item_damage2_type INT NOT NULL,
    item_damage3_min INT NOT NULL,
    item_damage3_max INT NOT NULL,
    item_damage3_type INT NOT NULL,
    item_damage4_min INT NOT NULL,
    item_damage4_max INT NOT NULL,
    item_damage4_type INT NOT NULL,
    item_damage5_min INT NOT NULL,
    item_damage5_max INT NOT NULL,
    item_damage5_type INT NOT NULL,
    /* Item damage END */

    armor INT NOT NULL,
    holy_resistance INT NOT NULL,
    fire_resistance INT NOT NULL,
    nature_resistance INT NOT NULL,
    frost_resistance INT NOT NULL,
    shadow_resistance INT NOT NULL,
    arcane_resistance INT NOT NULL,
    delay INT NOT NULL,
    ammo_type INT NOT NULL,
    ranged_mod_range FLOAT NOT NULL,

    /* Item spells START */
    spell1_id INT NOT NULL,
    spell1_trigger INT NOT NULL,
    spell1_charges INT NOT NULL,
    spell1_cooldown INT NOT NULL,
    spell1_category INT NOT NULL,
    spell1_category_cooldown INT NOT NULL,

    spell2_id INT NOT NULL,
    spell2_trigger INT NOT NULL,
    spell2_charges INT NOT NULL,
    spell2_cooldown INT NOT NULL,
    spell2_category INT NOT NULL,
    spell2_category_cooldown INT NOT NULL,

    spell3_id INT NOT NULL,
    spell3_trigger INT NOT NULL,
    spell3_charges INT NOT NULL,
    spell3_cooldown INT NOT NULL,
    spell3_category INT NOT NULL,
    spell3_category_cooldown INT NOT NULL,

    spell4_id INT NOT NULL,
    spell4_trigger INT NOT NULL,
    spell4_charges INT NOT NULL,
    spell4_cooldown INT NOT NULL,
    spell4_category INT NOT NULL,
    spell4_category_cooldown INT NOT NULL,

    spell5_id INT NOT NULL,
    spell5_trigger INT NOT NULL,
    spell5_charges INT NOT NULL,
    spell5_cooldown INT NOT NULL,
    spell5_category INT NOT NULL,
    spell5_category_cooldown INT NOT NULL,
    /* Item spells END */

    bonding INT NOT NULL,
    page_text INT NOT NULL,
    language_id INT NOT NULL,
    page_material INT NOT NULL,
    start_quest INT NOT NULL,
    lock_id INT NOT NULL,
    material INT NOT NULL,
    sheath INT NOT NULL,
    random_property INT NOT NULL,
    block INT NOT NULL,
    item_set INT NOT NULL,
    max_durability INT NOT NULL,
    area INT NOT NULL,
    map INT NOT NULL,
    bag_family INT NOT NULL,

    duration INT
);
CREATE TABLE IF NOT EXISTS race(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);
CREATE TABLE IF NOT EXISTS class(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);
CREATE TABLE IF NOT EXISTS character_display_id(
    race TINYINT NOT NULL,
    gender TINYINT NOT NULL,
    display_id INT NOT NULL,

    PRIMARY KEY(race, gender)
);
CREATE TABLE IF NOT EXISTS player_start_other_equipment(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    item_proto_id INT NOT NULL REFERENCES item_prototype
);
CREATE TABLE IF NOT EXISTS player_start_data(
    race TINYINT NOT NULL,
    class TINYINT NOT NULL,
    area INT NOT NULL,
    map INT NOT NULL,
    position_x FLOAT NOT NULL,
    position_y FLOAT NOT NULL,
    position_z FLOAT NOT NULL,
    orientation FLOAT NOT NULL,
    level TINYINT NOT NULL,

    /* Starting equipment START */
    equipment_head_id INT REFERENCES item_prototype,
    equipment_neck_id INT REFERENCES item_prototype,
    equipment_shoulders_id INT REFERENCES item_prototype,
    equipment_body_id INT REFERENCES item_prototype,
    equipment_chest_id INT REFERENCES item_prototype,
    equipment_waist_id INT REFERENCES item_prototype,
    equipment_legs_id INT REFERENCES item_prototype,
    equipment_feet_id INT REFERENCES item_prototype,
    equipment_wrists_id INT REFERENCES item_prototype,
    equipment_hands_id INT REFERENCES item_prototype,
    equipment_finger1_id INT REFERENCES item_prototype,
    equipment_finger2_id INT REFERENCES item_prototype,
    equipment_trinket1_id INT REFERENCES item_prototype,
    equipment_trinket2_id INT REFERENCES item_prototype,
    equipment_back_id INT REFERENCES item_prototype,
    equipment_mainhand_id INT REFERENCES item_prototype,
    equipment_offhand_id INT REFERENCES item_prototype,
    equipment_ranged_id INT REFERENCES item_prototype,
    equipment_tabard_id INT REFERENCES item_prototype,

    other_items_table_id INT REFERENCES player_start_other_equipment,
    /* Starting Equipmnet END */

    PRIMARY KEY(race, class)
);
/* ---------------- Game data END ---------------- */

CREATE TABLE IF NOT EXISTS item(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    prototype_id INTEGER NOT NULL,
    owner INTEGER REFERENCES character,
    creator INTEGER REFERENCES character,
    gift_creator INTEGER REFERENCES character,
    stack_count INTEGER NOT NULL,
    expires_in INTEGER,
    spell1_charges INTEGER,
    spell2_charges INTEGER,
    spell3_charges INTEGER,
    spell4_charges INTEGER,
    spell5_charges INTEGER,
    is_binded BOOLEAN NOT NULL,
    is_unlocked BOOLEAN NOT NULL,
    is_wrapped BOOLEAN NOT NULL,
    is_readable BOOLEAN NOT NULL,
    random_properties_id INTEGER NOT NULL,
    item_text_id INTEGER NOT NULL,
    durability INTEGER NOT NULL,
    
    enchantment1_id INTEGER NOT NULL,
    enchantment1_duration INTEGER NOT NULL,
    enchantment1_charges INTEGER NOT NULL,
    enchantment2_id INTEGER NOT NULL,
    enchantment2_duration INTEGER NOT NULL,
    enchantment2_charges INTEGER NOT NULL,
    enchantment3_id INTEGER NOT NULL,
    enchantment3_duration INTEGER NOT NULL,
    enchantment3_charges INTEGER NOT NULL,
    enchantment4_id INTEGER NOT NULL,
    enchantment4_duration INTEGER NOT NULL,
    enchantment4_charges INTEGER NOT NULL,
    enchantment5_id INTEGER NOT NULL,
    enchantment5_duration INTEGER NOT NULL,
    enchantment5_charges INTEGER NOT NULL,
    enchantment6_id INTEGER NOT NULL,
    enchantment6_duration INTEGER NOT NULL,
    enchantment6_charges INTEGER NOT NULL,
    enchantment7_id INTEGER NOT NULL,
    enchantment7_duration INTEGER NOT NULL,
    enchantment7_charges INTEGER NOT NULL,
    enchantment8_id INTEGER NOT NULL,
    enchantment8_duration INTEGER NOT NULL,
    enchantment8_charges INTEGER NOT NULL,
    enchantment9_id INTEGER NOT NULL,
    enchantment9_duration INTEGER NOT NULL,
    enchantment9_charges INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS character(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    account_id INT NOT NULL,
    name TEXT NOT NULL,
    race TINYINT NOT NULL,
    class TINYINT NOT NULL,
    gender BOOLEAN NOT NULL,
    skin TINYINT NOT NULL,
    face TINYINT NOT NULL,
    hair_style TINYINT NOT NULL,
    hair_color TINYINT NOT NULL,
    facial_hair TINYINT NOT NULL,
    level TINYINT NOT NULL,
    area INT NOT NULL,
    map INT NOT NULL,
    position_x FLOAT NOT NULL,
    position_y FLOAT NOT NULL,
    position_z FLOAT NOT NULL,
    orientation FLOAT NOT NULL,
    guild_id INT /* REFERENCES guild */,
    first_login BOOLEAN NOT NULL,
    display_id INT NOT NULL,

    /* Equipment START */
    equipment_head_id INT REFERENCES item,
    equipment_neck_id INT REFERENCES item,
    equipment_shoulders_id INT REFERENCES item,
    equipment_body_id INT REFERENCES item,
    equipment_chest_id INT REFERENCES item,
    equipment_waist_id INT REFERENCES item,
    equipment_legs_id INT REFERENCES item,
    equipment_feet_id INT REFERENCES item,
    equipment_wrists_id INT REFERENCES item,
    equipment_hands_id INT REFERENCES item,
    equipment_finger1_id INT REFERENCES item,
    equipment_finger2_id INT REFERENCES item,
    equipment_trinket1_id INT REFERENCES item,
    equipment_trinket2_id INT REFERENCES item,
    equipment_back_id INT REFERENCES item,
    equipment_mainhand_id INT REFERENCES item,
    equipment_offhand_id INT REFERENCES item,
    equipment_ranged_id INT REFERENCES item,
    equipment_tabard_id INT REFERENCES item
    /* Equipmnet END */
);