[package]
name = "gameserver"
version = "0.1.0"
authors = ["FoLZer <folzer.se@gmail.com>"]
edition = "2024"

[dependencies]
confy = "2.0.0"
log = "0.4.28"
log4rs = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
packets = { path = "./packets" }
lazy_static = "1.5.0"
rand = "0.9.2"
interprocess = { version = "2.2.3", features = ["tokio"] }
ipc_comms = { path = "../ipc_comms" }
itertools = "0.14.0"
sha1 = "0.10.6"
hex = "0.4.3"
common = { path = "./common" }
chrono = "0.4.42"
concurrent-queue = "2.5.0"
gameobjects = { path = "./gameobjects" }
bit-vec = "0.8.0"
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite", "macros", "migrate" ] }
