[package]
name = "packets"
version = "0.1.0"
authors = ["FoLZer <folzer.se@gmail.com>"]
edition = "2024"
license.workspace = true

[dependencies]
byteorder = "1.5.0"
lazy_static = "1.5.0"
macros = { path = "../../macros" }
tokio = "1.50.0"
common = { path = "../common" }
chrono = "0.4.44"
bit-vec = "0.9.0"
bitfield-struct = "0.12.1"
