[package]
name = "authserver"
version = "0.1.0"
authors = ["FoLZer <folzer.se@gmail.com>"]
edition = "2024"
license.workspace = true

[dependencies]
byteorder = "1.5.0"
confy = "2.0.0"
hex = "0.4.3"
interprocess = { version = "2.4.0", features = ["async", "tokio"] }
itertools = "0.14.0"
lazy_static = "1.5.0"
log = "0.4.29"
num-bigint = "0.4.6"
rand = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
sha1 = "0.10.6"
tokio = { version = "1.50.0", features = ["full"] }
ipc_comms = { path = "../ipc_comms" }
futures = "0.3.32"
authserver_migration = { path = "./authserver_migration" }
sea-orm = { version = "2.0.0-rc", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
authserver_entity = { path = "./authserver_entity" }
concurrent-queue = "2.5.0"
inquire = "0.9.4"
log4rs = "1.4.0"
inquire-derive = "0.9.4"
