use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Character::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Character::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Character::AccountId).integer().not_null())
                    .col(ColumnDef::new(Character::Name).text().not_null())
                    .col(ColumnDef::new(Character::Race).tiny_integer().not_null())
                    .col(ColumnDef::new(Character::Class).tiny_integer().not_null())
                    .col(ColumnDef::new(Character::Gender).tiny_integer().not_null())
                    .col(ColumnDef::new(Character::Skin).tiny_integer().not_null())
                    .col(ColumnDef::new(Character::Face).tiny_integer().not_null())
                    .col(
                        ColumnDef::new(Character::HairStyle)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::HairColor)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::FacialHair)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Character::Level).tiny_integer().not_null())
                    .col(ColumnDef::new(Character::Area).integer().not_null())
                    .col(ColumnDef::new(Character::Map).integer().not_null())
                    .col(ColumnDef::new(Character::PositionX).float().not_null())
                    .col(ColumnDef::new(Character::PositionY).float().not_null())
                    .col(ColumnDef::new(Character::PositionZ).float().not_null())
                    .col(ColumnDef::new(Character::Orientation).float().not_null())
                    .col(ColumnDef::new(Character::GuildId).integer().not_null())
                    .col(ColumnDef::new(Character::Flags).integer().not_null())
                    .col(ColumnDef::new(Character::FirstLogin).boolean().not_null())
                    .col(ColumnDef::new(Character::DisplayId).integer().not_null())
                    .col(
                        ColumnDef::new(Character::EquipmentHeadDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentHeadInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentNeckDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentNeckInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentShouldersDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentShouldersInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentBodyDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentBodyInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentChestDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentChestInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentWaistDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentWaistInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentLegsDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentLegsInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentFeetDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentFeetInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentWristsDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentWristsInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentHandsDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentHandsInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentFinger1DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentFinger1InventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentFinger2DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentFinger2InventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentTrinket1DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentTrinket1InventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentTrinket2DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentTrinket2InventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentBackDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentBackInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentMainhandDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentMainhandInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentOffhandDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentOffhandInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentRangedDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentRangedInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentTabardDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Character::EquipmentTabardInventoryType)
                            .integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(Character::Table).to_owned())
            .await?;

        Ok(())
    }
}

#[derive(DeriveIden)]
enum Character {
    Table,

    Id,
    AccountId,
    Name,
    Race,
    Class,
    Gender,
    Skin,
    Face,
    HairStyle,
    HairColor,
    FacialHair,
    Level,
    Area,
    Map,
    PositionX,
    PositionY,
    PositionZ,
    Orientation,
    GuildId,
    Flags,
    FirstLogin,
    DisplayId,

    EquipmentHeadDisplayId,
    EquipmentHeadInventoryType,
    EquipmentNeckDisplayId,
    EquipmentNeckInventoryType,
    EquipmentShouldersDisplayId,
    EquipmentShouldersInventoryType,
    EquipmentBodyDisplayId,
    EquipmentBodyInventoryType,
    EquipmentChestDisplayId,
    EquipmentChestInventoryType,
    EquipmentWaistDisplayId,
    EquipmentWaistInventoryType,
    EquipmentLegsDisplayId,
    EquipmentLegsInventoryType,
    EquipmentFeetDisplayId,
    EquipmentFeetInventoryType,
    EquipmentWristsDisplayId,
    EquipmentWristsInventoryType,
    EquipmentHandsDisplayId,
    EquipmentHandsInventoryType,
    EquipmentFinger1DisplayId,
    EquipmentFinger1InventoryType,
    EquipmentFinger2DisplayId,
    EquipmentFinger2InventoryType,
    EquipmentTrinket1DisplayId,
    EquipmentTrinket1InventoryType,
    EquipmentTrinket2DisplayId,
    EquipmentTrinket2InventoryType,
    EquipmentBackDisplayId,
    EquipmentBackInventoryType,
    EquipmentMainhandDisplayId,
    EquipmentMainhandInventoryType,
    EquipmentOffhandDisplayId,
    EquipmentOffhandInventoryType,
    EquipmentRangedDisplayId,
    EquipmentRangedInventoryType,
    EquipmentTabardDisplayId,
    EquipmentTabardInventoryType,
}
