use sea_orm_migration::{prelude::*, schema::*};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Race::Table)
                    .if_not_exists()
                    .col(pk_auto(Race::Id))
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Class::Table)
                    .if_not_exists()
                    .col(pk_auto(Class::Id))
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Gender::Table)
                    .if_not_exists()
                    .col(pk_auto(Gender::Id))
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(PlayerStartData::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(PlayerStartData::Race)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::Class)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PlayerStartData::AreaId).integer().not_null())
                    .col(ColumnDef::new(PlayerStartData::MapId).integer().not_null())
                    .col(
                        ColumnDef::new(PlayerStartData::PositionX)
                            .float()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::PositionY)
                            .float()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::PositionZ)
                            .float()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::Orientation)
                            .float()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::Level)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentHeadDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentHeadInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentNeckDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentNeckInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentShouldersDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentShouldersInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentBodyDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentBodyInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentChestDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentChestInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentWaistDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentWaistInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentLegsDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentLegsInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentFeetDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentFeetInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentWristsDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentWristsInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentHandsDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentHandsInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentFinger1DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentFinger1InventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentFinger2DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentFinger2InventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentTrinket1DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentTrinket1InventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentTrinket2DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentTrinket2InventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentBackDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentBackInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentMainhandDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentMainhandInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentOffhandDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentOffhandInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentRangedDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentRangedInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentTabardDisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::EquipmentTabardInventoryType)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartData::OtherEquipmentTableId)
                            .integer()
                            .not_null(),
                    )
                    //TODO: PlayerStartData::OtherEquipmentTableId -> PlayerStartOtherEquipment::TableId (one to many)
                    .primary_key(
                        &mut IndexCreateStatement::new()
                            .col(PlayerStartData::Race)
                            .col(PlayerStartData::Class),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(PlayerStartOtherEquipment::Table)
                    .if_not_exists()
                    .col(pk_auto(PlayerStartOtherEquipment::Id))
                    .col(
                        ColumnDef::new(PlayerStartOtherEquipment::TableId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartOtherEquipment::DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PlayerStartOtherEquipment::InventoryType)
                            .integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(CharacterDisplayId::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(CharacterDisplayId::Race)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CharacterDisplayId::Gender)
                            .tiny_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CharacterDisplayId::DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .primary_key(
                        &mut IndexCreateStatement::new()
                            .col(CharacterDisplayId::Race)
                            .col(CharacterDisplayId::Gender),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ItemPrototype::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ItemPrototype::Id)
                            .integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Class).integer().not_null())
                    .col(ColumnDef::new(ItemPrototype::SubClass).integer().not_null())
                    .col(ColumnDef::new(ItemPrototype::Name).string().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::Description)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::DisplayId)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Quality).integer().not_null())
                    .col(ColumnDef::new(ItemPrototype::BuyPrice).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::SellPrice)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::InventoryType)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::AllowableClass)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::AllowableRace)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemLevel)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::RequiredLevel)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::RequiredSkill)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::RequiredSkillRank)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::RequiredSpell)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::RequiredHonorRank)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::RequiredCityRank)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::RequiredReputationFaction)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::RequiredReputationRank)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::MaxCount).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::Stackable)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ContainerSlots)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat1Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat1Value)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat2Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat2Value)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat3Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat3Value)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat4Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat4Value)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat5Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat5Value)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat6Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat6Value)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat7Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat7Value)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat8Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat8Value)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat9Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat9Value)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat10Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemStat10Value)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage1Min)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage1Max)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage1Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage2Min)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage2Max)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage2Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage3Min)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage3Max)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage3Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage4Min)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage4Max)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage4Type)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage5Min)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage5Max)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ItemDamage5Type)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Armor).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::HolyResistance)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::FireResistance)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::NatureResistance)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::FrostResistance)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ShadowResistance)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::ArcaneResistance)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Delay).integer().not_null())
                    .col(ColumnDef::new(ItemPrototype::AmmoType).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::RangedModRange)
                            .float()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Spell1Id).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::Spell1Trigger)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell1Charges)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell1Cooldown)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell1Category)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell1CategoryCooldown)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Spell2Id).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::Spell2Trigger)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell2Charges)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell2Cooldown)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell2Category)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell2CategoryCooldown)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Spell3Id).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::Spell3Trigger)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell3Charges)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell3Cooldown)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell3Category)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell3CategoryCooldown)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Spell4Id).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::Spell4Trigger)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell4Charges)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell4Cooldown)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell4Category)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell4CategoryCooldown)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Spell5Id).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::Spell5Trigger)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell5Charges)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell5Cooldown)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell5Category)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::Spell5CategoryCooldown)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Bonding).integer().not_null())
                    .col(ColumnDef::new(ItemPrototype::PageText).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::LanguageId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::PageMaterial)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ItemPrototype::StartQuest)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::LockId).integer().not_null())
                    .col(ColumnDef::new(ItemPrototype::Material).integer().not_null())
                    .col(ColumnDef::new(ItemPrototype::Sheath).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::RandomProperty)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Block).integer().not_null())
                    .col(ColumnDef::new(ItemPrototype::ItemSet).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::MaxDurability)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ItemPrototype::Area).integer().not_null())
                    .col(ColumnDef::new(ItemPrototype::Map).integer().not_null())
                    .col(
                        ColumnDef::new(ItemPrototype::BagFamily)
                            .integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(Race::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Class::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Gender::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(PlayerStartData::Table).to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(PlayerStartOtherEquipment::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(CharacterDisplayId::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ItemPrototype::Table).to_owned())
            .await?;

        Ok(())
    }
}

#[derive(DeriveIden)]
enum Race {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum Class {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum Gender {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum PlayerStartData {
    Table,

    Race,
    Class,

    AreaId,
    MapId,
    PositionX,
    PositionY,
    PositionZ,
    Orientation,
    Level,

    EquipmentHeadDisplayId,
    EquipmentHeadInventoryType,
    EquipmentNeckDisplayId,
    EquipmentNeckInventoryType,
    EquipmentShouldersDisplayId,
    EquipmentShouldersInventoryType,
    EquipmentBodyDisplayId,
    EquipmentBodyInventoryType,
    EquipmentChestDisplayId,
    EquipmentChestInventoryType,
    EquipmentWaistDisplayId,
    EquipmentWaistInventoryType,
    EquipmentLegsDisplayId,
    EquipmentLegsInventoryType,
    EquipmentFeetDisplayId,
    EquipmentFeetInventoryType,
    EquipmentWristsDisplayId,
    EquipmentWristsInventoryType,
    EquipmentHandsDisplayId,
    EquipmentHandsInventoryType,
    EquipmentFinger1DisplayId,
    EquipmentFinger1InventoryType,
    EquipmentFinger2DisplayId,
    EquipmentFinger2InventoryType,
    EquipmentTrinket1DisplayId,
    EquipmentTrinket1InventoryType,
    EquipmentTrinket2DisplayId,
    EquipmentTrinket2InventoryType,
    EquipmentBackDisplayId,
    EquipmentBackInventoryType,
    EquipmentMainhandDisplayId,
    EquipmentMainhandInventoryType,
    EquipmentOffhandDisplayId,
    EquipmentOffhandInventoryType,
    EquipmentRangedDisplayId,
    EquipmentRangedInventoryType,
    EquipmentTabardDisplayId,
    EquipmentTabardInventoryType,

    OtherEquipmentTableId,
}

#[derive(DeriveIden)]
enum PlayerStartOtherEquipment {
    Table,

    Id,

    TableId,

    DisplayId,
    InventoryType,
}

#[derive(DeriveIden)]
enum CharacterDisplayId {
    Table,

    Race,
    Gender,

    DisplayId,
}

#[derive(DeriveIden)]
pub(crate) enum ItemPrototype {
    Table,

    Id,

    Class,
    SubClass,
    Name,
    Description,
    DisplayId,
    Quality,
    BuyPrice,
    SellPrice,
    InventoryType,
    AllowableClass,
    AllowableRace,
    ItemLevel,
    RequiredLevel,
    RequiredSkill,
    RequiredSkillRank,
    RequiredSpell,
    RequiredHonorRank,
    RequiredCityRank,
    RequiredReputationFaction,
    RequiredReputationRank,
    MaxCount,
    Stackable,
    ContainerSlots,

    ItemStat1Type,
    ItemStat1Value,
    ItemStat2Type,
    ItemStat2Value,
    ItemStat3Type,
    ItemStat3Value,
    ItemStat4Type,
    ItemStat4Value,
    ItemStat5Type,
    ItemStat5Value,
    ItemStat6Type,
    ItemStat6Value,
    ItemStat7Type,
    ItemStat7Value,
    ItemStat8Type,
    ItemStat8Value,
    ItemStat9Type,
    ItemStat9Value,
    ItemStat10Type,
    ItemStat10Value,

    ItemDamage1Min,
    ItemDamage1Max,
    ItemDamage1Type,
    ItemDamage2Min,
    ItemDamage2Max,
    ItemDamage2Type,
    ItemDamage3Min,
    ItemDamage3Max,
    ItemDamage3Type,
    ItemDamage4Min,
    ItemDamage4Max,
    ItemDamage4Type,
    ItemDamage5Min,
    ItemDamage5Max,
    ItemDamage5Type,

    Armor,
    HolyResistance,
    FireResistance,
    NatureResistance,
    FrostResistance,
    ShadowResistance,
    ArcaneResistance,

    Delay,
    AmmoType,
    RangedModRange,

    Spell1Id,
    Spell1Trigger,
    Spell1Charges,
    Spell1Cooldown,
    Spell1Category,
    Spell1CategoryCooldown,
    Spell2Id,
    Spell2Trigger,
    Spell2Charges,
    Spell2Cooldown,
    Spell2Category,
    Spell2CategoryCooldown,
    Spell3Id,
    Spell3Trigger,
    Spell3Charges,
    Spell3Cooldown,
    Spell3Category,
    Spell3CategoryCooldown,
    Spell4Id,
    Spell4Trigger,
    Spell4Charges,
    Spell4Cooldown,
    Spell4Category,
    Spell4CategoryCooldown,
    Spell5Id,
    Spell5Trigger,
    Spell5Charges,
    Spell5Cooldown,
    Spell5Category,
    Spell5CategoryCooldown,

    Bonding,
    PageText,
    LanguageId,
    PageMaterial,
    StartQuest,
    LockId,
    Material,
    Sheath,
    RandomProperty,
    Block,
    ItemSet,
    MaxDurability,
    Area,
    Map,
    BagFamily,
}
