//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "character_display_id")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub race: i8,
    #[sea_orm(primary_key, auto_increment = false)]
    pub gender: i8,
    pub display_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
