//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "character")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub account_id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub race: i8,
    pub class: i8,
    pub gender: i8,
    pub skin: i8,
    pub face: i8,
    pub hair_style: i8,
    pub hair_color: i8,
    pub facial_hair: i8,
    pub level: i8,
    pub area: i64,
    pub map: i64,
    #[sea_orm(column_type = "Float")]
    pub position_x: f32,
    #[sea_orm(column_type = "Float")]
    pub position_y: f32,
    #[sea_orm(column_type = "Float")]
    pub position_z: f32,
    #[sea_orm(column_type = "Float")]
    pub orientation: f32,
    pub guild_id: i64,
    pub flags: i64,
    pub first_login: bool,
    pub display_id: i64,
    pub equipment_head: Option<i64>,
    pub equipment_neck: Option<i64>,
    pub equipment_shoulders: Option<i64>,
    pub equipment_body: Option<i64>,
    pub equipment_chest: Option<i64>,
    pub equipment_waist: Option<i64>,
    pub equipment_legs: Option<i64>,
    pub equipment_feet: Option<i64>,
    pub equipment_wrists: Option<i64>,
    pub equipment_hands: Option<i64>,
    pub equipment_finger1: Option<i64>,
    pub equipment_finger2: Option<i64>,
    pub equipment_trinket1: Option<i64>,
    pub equipment_trinket2: Option<i64>,
    pub equipment_back: Option<i64>,
    pub equipment_mainhand: Option<i64>,
    pub equipment_offhand: Option<i64>,
    pub equipment_ranged: Option<i64>,
    pub equipment_tabard: Option<i64>,
    pub bag1: Option<i64>,
    pub bag2: Option<i64>,
    pub bag3: Option<i64>,
    pub bag4: Option<i64>,
    pub main_backpack1: Option<i64>,
    pub main_backpack2: Option<i64>,
    pub main_backpack3: Option<i64>,
    pub main_backpack4: Option<i64>,
    pub main_backpack5: Option<i64>,
    pub main_backpack6: Option<i64>,
    pub main_backpack7: Option<i64>,
    pub main_backpack8: Option<i64>,
    pub main_backpack9: Option<i64>,
    pub main_backpack10: Option<i64>,
    pub main_backpack11: Option<i64>,
    pub main_backpack12: Option<i64>,
    pub main_backpack13: Option<i64>,
    pub main_backpack14: Option<i64>,
    pub main_backpack15: Option<i64>,
    pub main_backpack16: Option<i64>,
    pub bank1: Option<i64>,
    pub bank2: Option<i64>,
    pub bank3: Option<i64>,
    pub bank4: Option<i64>,
    pub bank5: Option<i64>,
    pub bank6: Option<i64>,
    pub bank7: Option<i64>,
    pub bank8: Option<i64>,
    pub bank9: Option<i64>,
    pub bank10: Option<i64>,
    pub bank11: Option<i64>,
    pub bank12: Option<i64>,
    pub bank13: Option<i64>,
    pub bank14: Option<i64>,
    pub bank15: Option<i64>,
    pub bank16: Option<i64>,
    pub bank17: Option<i64>,
    pub bank18: Option<i64>,
    pub bank19: Option<i64>,
    pub bank20: Option<i64>,
    pub bank21: Option<i64>,
    pub bank22: Option<i64>,
    pub bank23: Option<i64>,
    pub bank24: Option<i64>,
    pub bank25: Option<i64>,
    pub bank26: Option<i64>,
    pub bank27: Option<i64>,
    pub bank28: Option<i64>,
    pub bank_bag1: Option<i64>,
    pub bank_bag2: Option<i64>,
    pub bank_bag3: Option<i64>,
    pub bank_bag4: Option<i64>,
    pub bank_bag5: Option<i64>,
    pub bank_bag6: Option<i64>,
    pub bank_bag7: Option<i64>,
    pub vendor_buyback1: Option<i64>,
    pub vendor_buyback2: Option<i64>,
    pub vendor_buyback3: Option<i64>,
    pub vendor_buyback4: Option<i64>,
    pub vendor_buyback5: Option<i64>,
    pub vendor_buyback6: Option<i64>,
    pub vendor_buyback7: Option<i64>,
    pub vendor_buyback8: Option<i64>,
    pub vendor_buyback9: Option<i64>,
    pub vendor_buyback10: Option<i64>,
    pub vendor_buyback11: Option<i64>,
    pub vendor_buyback12: Option<i64>,
    pub keyring1: Option<i64>,
    pub keyring2: Option<i64>,
    pub keyring3: Option<i64>,
    pub keyring4: Option<i64>,
    pub keyring5: Option<i64>,
    pub keyring6: Option<i64>,
    pub keyring7: Option<i64>,
    pub keyring8: Option<i64>,
    pub keyring9: Option<i64>,
    pub keyring10: Option<i64>,
    pub keyring11: Option<i64>,
    pub keyring12: Option<i64>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item98",
        from = "keyring12",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_98: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item97",
        from = "keyring11",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_97: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item96",
        from = "keyring10",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_96: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item95",
        from = "keyring9",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_95: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item94",
        from = "keyring8",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_94: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item93",
        from = "keyring7",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_93: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item92",
        from = "keyring6",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_92: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item91",
        from = "keyring5",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_91: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item90",
        from = "keyring4",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_90: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item89",
        from = "keyring3",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_89: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item88",
        from = "keyring2",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_88: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item87",
        from = "keyring1",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_87: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item86",
        from = "vendor_buyback12",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_86: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item85",
        from = "vendor_buyback11",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_85: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item84",
        from = "vendor_buyback10",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_84: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item83",
        from = "vendor_buyback9",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_83: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item82",
        from = "vendor_buyback8",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_82: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item81",
        from = "vendor_buyback7",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_81: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item80",
        from = "vendor_buyback6",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_80: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item79",
        from = "vendor_buyback5",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_79: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item78",
        from = "vendor_buyback4",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_78: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item77",
        from = "vendor_buyback3",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_77: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item76",
        from = "vendor_buyback2",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_76: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item75",
        from = "vendor_buyback1",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_75: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item74",
        from = "bank_bag7",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_74: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item73",
        from = "bank_bag6",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_73: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item72",
        from = "bank_bag5",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_72: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item71",
        from = "bank_bag4",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_71: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item70",
        from = "bank_bag3",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_70: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item69",
        from = "bank_bag2",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_69: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item68",
        from = "bank_bag1",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_68: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item67",
        from = "bank28",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_67: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item66",
        from = "bank27",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_66: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item65",
        from = "bank26",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_65: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item64",
        from = "bank25",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_64: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item63",
        from = "bank24",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_63: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item62",
        from = "bank23",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_62: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item61",
        from = "bank22",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_61: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item60",
        from = "bank21",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_60: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item59",
        from = "bank20",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_59: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item58",
        from = "bank19",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_58: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item57",
        from = "bank18",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_57: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item56",
        from = "bank17",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_56: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item55",
        from = "bank16",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_55: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item54",
        from = "bank15",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_54: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item53",
        from = "bank14",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_53: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item52",
        from = "bank13",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_52: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item51",
        from = "bank12",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_51: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item50",
        from = "bank11",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_50: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item49",
        from = "bank10",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_49: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item48",
        from = "bank9",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_48: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item47",
        from = "bank8",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_47: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item46",
        from = "bank7",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_46: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item45",
        from = "bank6",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_45: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item44",
        from = "bank5",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_44: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item43",
        from = "bank4",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_43: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item42",
        from = "bank3",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_42: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item41",
        from = "bank2",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_41: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item40",
        from = "bank1",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_40: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item39",
        from = "main_backpack16",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_39: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item38",
        from = "main_backpack15",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_38: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item37",
        from = "main_backpack14",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_37: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item36",
        from = "main_backpack13",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_36: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item35",
        from = "main_backpack12",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_35: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item34",
        from = "main_backpack11",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_34: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item33",
        from = "main_backpack10",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_33: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item32",
        from = "main_backpack9",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_32: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item31",
        from = "main_backpack8",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_31: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item30",
        from = "main_backpack7",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_30: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item29",
        from = "main_backpack6",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_29: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item28",
        from = "main_backpack5",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_28: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item27",
        from = "main_backpack4",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_27: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item26",
        from = "main_backpack3",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_26: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item25",
        from = "main_backpack2",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_25: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item24",
        from = "main_backpack1",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_24: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item23",
        from = "bag4",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_23: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item22",
        from = "bag3",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_22: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item21",
        from = "bag2",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_21: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item20",
        from = "bag1",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_20: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item19",
        from = "equipment_tabard",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_19: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item18",
        from = "equipment_ranged",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_18: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item17",
        from = "equipment_offhand",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_17: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item16",
        from = "equipment_mainhand",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_16: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item15",
        from = "equipment_back",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_15: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item14",
        from = "equipment_trinket2",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_14: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item13",
        from = "equipment_trinket1",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_13: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item12",
        from = "equipment_finger2",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_12: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item11",
        from = "equipment_finger1",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_11: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item10",
        from = "equipment_hands",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_10: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item9",
        from = "equipment_wrists",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_9: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item8",
        from = "equipment_feet",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_8: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item7",
        from = "equipment_legs",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_7: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item6",
        from = "equipment_waist",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_6: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item5",
        from = "equipment_chest",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_5: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item4",
        from = "equipment_body",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_4: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item3",
        from = "equipment_shoulders",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_3: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item2",
        from = "equipment_neck",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_2: HasOne<super::item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Item1",
        from = "equipment_head",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_1: HasOne<super::item::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
