//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_display_id")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub race: i8,
    #[sea_orm(primary_key, auto_increment = false)]
    pub gender: i8,
    pub display_id: i64,
}

impl ActiveModelBehavior for ActiveModel {}
