//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub item_prototype_id: u32,
    pub owner_id: u32,
    pub creator_id: Option<u32>,
    pub gift_creator_id: Option<u32>,
    pub stack_count: u32,
    pub expires_in: Option<u32>,
    pub spell1_charges: Option<u32>,
    pub spell2_charges: Option<u32>,
    pub spell3_charges: Option<u32>,
    pub spell4_charges: Option<u32>,
    pub spell5_charges: Option<u32>,
    pub is_binded: bool,
    pub is_unlocked: bool,
    pub is_wrapped: bool,
    pub is_readable: bool,
    pub random_properties_id: u32,
    pub item_text_id: u32,
    pub durability: u32,
    pub enchantment1_id: u32,
    pub enchantment1_duration: u32,
    pub enchantment1_charges: u32,
    pub enchantment2_id: u32,
    pub enchantment2_duration: u32,
    pub enchantment2_charges: u32,
    pub enchantment3_id: u32,
    pub enchantment3_duration: u32,
    pub enchantment3_charges: u32,
    pub enchantment4_id: u32,
    pub enchantment4_duration: u32,
    pub enchantment4_charges: u32,
    pub enchantment5_id: u32,
    pub enchantment5_duration: u32,
    pub enchantment5_charges: u32,
    pub enchantment6_id: u32,
    pub enchantment6_duration: u32,
    pub enchantment6_charges: u32,
    pub enchantment7_id: u32,
    pub enchantment7_duration: u32,
    pub enchantment7_charges: u32,
    pub enchantment8_id: u32,
    pub enchantment8_duration: u32,
    pub enchantment8_charges: u32,
    pub enchantment9_id: u32,
    pub enchantment9_duration: u32,
    pub enchantment9_charges: u32,

    #[sea_orm(
        belongs_to,
        relation_enum = "Owner",
        from = "owner_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub owner: HasOne<super::character::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Prototype",
        from = "item_prototype_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub prototype: HasOne<super::item_prototype::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
