//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub item_prototype_id: i64,
    pub owner: i64,
    pub creator: Option<i64>,
    pub gift_creator: Option<i64>,
    pub stack_count: i64,
    pub expires_in: Option<i64>,
    pub spell1_charges: Option<i64>,
    pub spell2_charges: Option<i64>,
    pub spell3_charges: Option<i64>,
    pub spell4_charges: Option<i64>,
    pub spell5_charges: Option<i64>,
    pub is_binded: bool,
    pub is_unlocked: bool,
    pub is_wrapped: bool,
    pub is_readable: bool,
    pub random_properties_id: i64,
    pub item_text_id: i64,
    pub durability: i64,
    pub enchantment1_id: i64,
    pub enchantment1_duration: i64,
    pub enchantment1_charges: i64,
    pub enchantment2_id: i64,
    pub enchantment2_duration: i64,
    pub enchantment2_charges: i64,
    pub enchantment3_id: i64,
    pub enchantment3_duration: i64,
    pub enchantment3_charges: i64,
    pub enchantment4_id: i64,
    pub enchantment4_duration: i64,
    pub enchantment4_charges: i64,
    pub enchantment5_id: i64,
    pub enchantment5_duration: i64,
    pub enchantment5_charges: i64,
    pub enchantment6_id: i64,
    pub enchantment6_duration: i64,
    pub enchantment6_charges: i64,
    pub enchantment7_id: i64,
    pub enchantment7_duration: i64,
    pub enchantment7_charges: i64,
    pub enchantment8_id: i64,
    pub enchantment8_duration: i64,
    pub enchantment8_charges: i64,
    pub enchantment9_id: i64,
    pub enchantment9_duration: i64,
    pub enchantment9_charges: i64,
    #[sea_orm(
        belongs_to,
        relation_enum = "Character3",
        from = "gift_creator",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub character_3: HasOne<super::character::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Character2",
        from = "creator",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub character_2: HasOne<super::character::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Character1",
        from = "owner",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub character_1: HasOne<super::character::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
