//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub item_prototype_id: i32,
    pub owner: i32,
    pub creator: Option<i32>,
    pub gift_creator: Option<i32>,
    pub stack_count: i32,
    pub expires_in: Option<i32>,
    pub spell1_charges: Option<i32>,
    pub spell2_charges: Option<i32>,
    pub spell3_charges: Option<i32>,
    pub spell4_charges: Option<i32>,
    pub spell5_charges: Option<i32>,
    pub is_binded: bool,
    pub is_unlocked: bool,
    pub is_wrapped: bool,
    pub is_readable: bool,
    pub random_properties_id: i32,
    pub item_text_id: i32,
    pub durability: i32,
    pub enchantment1_id: i32,
    pub enchantment1_duration: i32,
    pub enchantment1_charges: i32,
    pub enchantment2_id: i32,
    pub enchantment2_duration: i32,
    pub enchantment2_charges: i32,
    pub enchantment3_id: i32,
    pub enchantment3_duration: i32,
    pub enchantment3_charges: i32,
    pub enchantment4_id: i32,
    pub enchantment4_duration: i32,
    pub enchantment4_charges: i32,
    pub enchantment5_id: i32,
    pub enchantment5_duration: i32,
    pub enchantment5_charges: i32,
    pub enchantment6_id: i32,
    pub enchantment6_duration: i32,
    pub enchantment6_charges: i32,
    pub enchantment7_id: i32,
    pub enchantment7_duration: i32,
    pub enchantment7_charges: i32,
    pub enchantment8_id: i32,
    pub enchantment8_duration: i32,
    pub enchantment8_charges: i32,
    pub enchantment9_id: i32,
    pub enchantment9_duration: i32,
    pub enchantment9_charges: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::character::Entity",
        from = "Column::GiftCreator",
        to = "super::character::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Character3,
    #[sea_orm(
        belongs_to = "super::character::Entity",
        from = "Column::Creator",
        to = "super::character::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Character2,
    #[sea_orm(
        belongs_to = "super::character::Entity",
        from = "Column::Owner",
        to = "super::character::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Character1,
}

impl ActiveModelBehavior for ActiveModel {}
