//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub mod prelude;

pub mod character;
pub mod character_display_id;
pub mod class;
pub mod gender;
pub mod item;
pub mod item_prototype;
pub mod player_start_data;
pub mod player_start_other_equipment;
pub mod race;
