//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "player_start_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub race: i8,
    #[sea_orm(primary_key, auto_increment = false)]
    pub class: i8,
    pub area_id: i32,
    pub map_id: i32,
    #[sea_orm(column_type = "Float")]
    pub position_x: f32,
    #[sea_orm(column_type = "Float")]
    pub position_y: f32,
    #[sea_orm(column_type = "Float")]
    pub position_z: f32,
    #[sea_orm(column_type = "Float")]
    pub orientation: f32,
    pub level: i8,
    pub equipment_head_id: Option<i32>,
    pub equipment_neck_id: Option<i32>,
    pub equipment_shoulders_id: Option<i32>,
    pub equipment_body_id: Option<i32>,
    pub equipment_chest_id: Option<i32>,
    pub equipment_waist_id: Option<i32>,
    pub equipment_legs_id: Option<i32>,
    pub equipment_feet_id: Option<i32>,
    pub equipment_wrists_id: Option<i32>,
    pub equipment_hands_id: Option<i32>,
    pub equipment_finger1_id: Option<i32>,
    pub equipment_finger2_id: Option<i32>,
    pub equipment_trinket1_id: Option<i32>,
    pub equipment_trinket2_id: Option<i32>,
    pub equipment_back_id: Option<i32>,
    pub equipment_mainhand_id: Option<i32>,
    pub equipment_offhand_id: Option<i32>,
    pub equipment_ranged_id: Option<i32>,
    pub equipment_tabard_id: Option<i32>,
    pub other_equipment_table_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentTabardId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype19,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentRangedId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype18,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentOffhandId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype17,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentMainhandId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype16,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentBackId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype15,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentTrinket2Id",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype14,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentTrinket1Id",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype13,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentFinger2Id",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype12,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentFinger1Id",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype11,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentHandsId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype10,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentWristsId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype9,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentFeetId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype8,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentLegsId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype7,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentWaistId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype6,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentChestId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype5,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentBodyId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype4,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentShouldersId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype3,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentNeckId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype2,
    #[sea_orm(
        belongs_to = "super::item_prototype::Entity",
        from = "Column::EquipmentHeadId",
        to = "super::item_prototype::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPrototype1,
}

impl ActiveModelBehavior for ActiveModel {}
