//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "player_start_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub race: i8,
    #[sea_orm(primary_key, auto_increment = false)]
    pub class: i8,
    pub area_id: i64,
    pub map_id: i64,
    #[sea_orm(column_type = "Float")]
    pub position_x: f32,
    #[sea_orm(column_type = "Float")]
    pub position_y: f32,
    #[sea_orm(column_type = "Float")]
    pub position_z: f32,
    #[sea_orm(column_type = "Float")]
    pub orientation: f32,
    pub level: i8,
    pub equipment_head_id: Option<i64>,
    pub equipment_neck_id: Option<i64>,
    pub equipment_shoulders_id: Option<i64>,
    pub equipment_body_id: Option<i64>,
    pub equipment_chest_id: Option<i64>,
    pub equipment_waist_id: Option<i64>,
    pub equipment_legs_id: Option<i64>,
    pub equipment_feet_id: Option<i64>,
    pub equipment_wrists_id: Option<i64>,
    pub equipment_hands_id: Option<i64>,
    pub equipment_finger1_id: Option<i64>,
    pub equipment_finger2_id: Option<i64>,
    pub equipment_trinket1_id: Option<i64>,
    pub equipment_trinket2_id: Option<i64>,
    pub equipment_back_id: Option<i64>,
    pub equipment_mainhand_id: Option<i64>,
    pub equipment_offhand_id: Option<i64>,
    pub equipment_ranged_id: Option<i64>,
    pub equipment_tabard_id: Option<i64>,
    pub other_equipment_table_id: i64,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype19",
        from = "equipment_tabard_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_19: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype18",
        from = "equipment_ranged_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_18: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype17",
        from = "equipment_offhand_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_17: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype16",
        from = "equipment_mainhand_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_16: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype15",
        from = "equipment_back_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_15: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype14",
        from = "equipment_trinket2_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_14: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype13",
        from = "equipment_trinket1_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_13: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype12",
        from = "equipment_finger2_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_12: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype11",
        from = "equipment_finger1_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_11: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype10",
        from = "equipment_hands_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_10: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype9",
        from = "equipment_wrists_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_9: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype8",
        from = "equipment_feet_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_8: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype7",
        from = "equipment_legs_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_7: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype6",
        from = "equipment_waist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_6: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype5",
        from = "equipment_chest_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_5: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype4",
        from = "equipment_body_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_4: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype3",
        from = "equipment_shoulders_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_3: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype2",
        from = "equipment_neck_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_2: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ItemPrototype1",
        from = "equipment_head_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub item_prototype_1: HasOne<super::item_prototype::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
