//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "player_start_other_equipment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub table_id: i64,
    pub display_id: i64,
    pub inventory_type: i64,
}

impl ActiveModelBehavior for ActiveModel {}
