//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "player_start_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub race: u8,
    #[sea_orm(primary_key, auto_increment = false)]
    pub class: u8,
    pub area_id: u32,
    pub map_id: u32,
    #[sea_orm(column_type = "Float")]
    pub position_x: f32,
    #[sea_orm(column_type = "Float")]
    pub position_y: f32,
    #[sea_orm(column_type = "Float")]
    pub position_z: f32,
    #[sea_orm(column_type = "Float")]
    pub orientation: f32,
    pub level: u8,
    pub equipment_head_id: Option<i64>,
    pub equipment_neck_id: Option<i64>,
    pub equipment_shoulders_id: Option<i64>,
    pub equipment_body_id: Option<i64>,
    pub equipment_chest_id: Option<i64>,
    pub equipment_waist_id: Option<i64>,
    pub equipment_legs_id: Option<i64>,
    pub equipment_feet_id: Option<i64>,
    pub equipment_wrists_id: Option<i64>,
    pub equipment_hands_id: Option<i64>,
    pub equipment_finger1_id: Option<i64>,
    pub equipment_finger2_id: Option<i64>,
    pub equipment_trinket1_id: Option<i64>,
    pub equipment_trinket2_id: Option<i64>,
    pub equipment_back_id: Option<i64>,
    pub equipment_mainhand_id: Option<i64>,
    pub equipment_offhand_id: Option<i64>,
    pub equipment_ranged_id: Option<i64>,
    pub equipment_tabard_id: Option<i64>,
    pub other_equipment_table_id: i64,
    /* 
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentTabard",
        from = "equipment_tabard_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_tabard: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentRanged",
        from = "equipment_ranged_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_ranged: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentOffhand",
        from = "equipment_offhand_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_offhand: HasOne<super::item_prototype::Entity>,
    */
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentMainhand",
        from = "equipment_mainhand_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_mainhand: HasOne<super::item_prototype::Entity>,
    /* 
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentBack",
        from = "equipment_back_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_back: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentTrinket2",
        from = "equipment_trinket2_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_trinket2: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentTrinket1",
        from = "equipment_trinket1_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_trinket1: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentFinger2",
        from = "equipment_finger2_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_finger2: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentFinger1",
        from = "equipment_finger1_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_finger1: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentHands",
        from = "equipment_hands_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_hands: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentWrists",
        from = "equipment_wrists_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_wrists: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentFeet",
        from = "equipment_feet_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_feet: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentLegs",
        from = "equipment_legs_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_legs: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentWaist",
        from = "equipment_waist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_waist: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentChest",
        from = "equipment_chest_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_chest: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentBody",
        from = "equipment_body_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_body: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentShoulders",
        from = "equipment_shoulders_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_shoulders: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentNeck",
        from = "equipment_neck_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_neck: HasOne<super::item_prototype::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "EquipmentHead",
        from = "equipment_head_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub equipment_head: HasOne<super::item_prototype::Entity>,
    */
}

impl ActiveModelBehavior for ActiveModel {}
